name: Generate Migration Script with EF Core DbContexts
description: Generate SQL scripts for all DbContext instances found inside a project

branding:
  color: gray-dark
  icon: database

inputs:
  project-dir:
    description: The path to the directory of the project containing the DbContexts
    required: true
  output-file:
    description: The name of the generated SQL script
    required: true
  ef-core-version:
    description: The version of the EF Core tools to use to generate scripts (defaults to latest)
    required: false
    default: "*"
  build-configuration:
    description: The build configuration to be used
    required: false
    default: Release

runs:
  using: composite
  steps:
    - name: Install EF Core Tools version ${{ inputs.ef-core-version }}
      shell: bash
      run: dotnet tool install --global dotnet-ef --version ${{ inputs.ef-core-version }}
    - name: Generate SQL scripts
      shell: bash
      run: |
        ARGS="--no-build -s ${{ inputs.project-dir }} -p ${{ inputs.project-dir }} --configuration ${{ inputs.build-configuration }}"
        DB_CONTEXT_LIST=`dotnet ef dbcontext list ${ARGS}`
        for DB_CONTEXT in ${DB_CONTEXT_LIST} ; do
          dotnet ef migrations script -i -c ${DB_CONTEXT} -o /tmp/sql-script-generation/migrate_${DB_CONTEXT}.sql
        done
    - name: Merge SQL scripts
      shell: bash
      run: |
        OUTPUT_FILE_NAME="${{ inputs.output-file }}"
        mkdir -p "${OUTPUT_FILE_NAME%/*}"
        for SQL_FILE_NAME in /tmp/sql-script-generation/*.sql
        do
          cat $SQL_FILE_NAME >> ${{ inputs.output-file }}
        done
